# Generated by Django 5.2 on 2025-05-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_departurepage_votes_count_vote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departurepage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='departure_images/'),
        ),
        migrations.AlterField(
            model_name='departurepage',
            name='tone',
            field=models.CharField(choices=[('liberating_joy', 'Liberating Joy'), ('sadness', 'Sadness'), ('disgust', 'Disgust'), ('explosive_anger', 'Explosive Anger'), ('detached_irony', 'Detached Irony'), ('hilarious', 'Hilarious'), ('poetic', 'Poetic'), ('existential_void', 'Existential Void'), ('acceptance', 'Acceptance'), ('confused', 'Confused')], default='sadness', max_length=25),
        ),
    ]
